config/routes.rb
StudyNetwork::Application.routes.draw do
  devise_for :users, :skip => [:sessions, :registrations]
  as :user do
    match "login" =>        "sessions#new", as: :new_user_session, via: [:get, :post] # sending to custom sessions for modal option
    post "login_user" =>    "sessions#create", as: :user_session
    delete "logout_user" => "sessions#destroy", as: :destroy_user_session

    get "/register" =>    "registrations#new", as: :new_user_registration
    get "/u/edit" =>      "registrations#edit", as: :edit_user_registration
    post "/register" =>   "registrations#create", as: :user_registration
    patch "/register" =>  "registrations#update"
    put "/register" =>    "registrations#update"
    delete "/register" => "registrations#destroy"

    get "/u/delete_account" => "registrations#delete_account", via: :get

    get "/u/:id" => "registrations#show", as: :user
  end

  resources :n, as: :notes, controller: :notes do
    member do
      get "forks"
    end
  end

  namespace :admin do
    scope "n", as: "note" do
      get ":id" =>             "notes#show"
      patch ":id/hide" =>      "notes#hide", as: :hide
      patch ":id/unhide" =>    "notes#unhide", as: :unhide
      patch ":id/feature" =>   "notes#feature", as: :feature
      patch ":id/unfeature" => "notes#unfeature", as: :unfeature
    end
  end

  match "goals/info" => "goals#info", as: :goals_info, via: [:get, :post]
  resources :goals do
    member do
      post   "t" =>    :create_todo
      put    ":tid" => :update_todo
      delete ":tid" => :destroy_todo
    end
  end

  get "/notifications" =>       "notifications#index", as: :notifications
  get "/notifications/count" => "notifications#count"
  get "/notifications/:id" =>   "notifications#show", as: :notification
  
  post "/v/:model/:id/:value" => "votes#create"

  get "/about" =>     "home#about"
  get "/changelog" => "home#changelog"

  get "/nw" => "home#marked_as_nw", as: :nw

  root "home#index"

  get "bgoals" => "home#beta"

end

app/models/note.rb
class Note < ActiveRecord::Base
  include ActionView::Helpers::DateHelper # For time ago in words

  include PgSearch
  pg_search_scope :search_by_title_short_text,
    against:  [:title, :short_text],
    using:    { tsearch: { dictionary: "english" } },
    ignoring: :accents

  URL_REGEXP = URI::Parser.new.make_regexp(['https'])

  acts_as_paranoid

  belongs_to :user
  has_many :votes, as: :votable, dependent: :destroy
  has_many :page_views, as: :viewable, dependent: :destroy

  # Allows for: note.forks and note.fork_ids
  has_many :forks, class_name: "Note", foreign_key: "forked_from"
  # Allows for: note.original_fork
  belongs_to :original_fork, class_name: "Note", foreign_key: "forked_from"

  belongs_to :hider, class_name: "User", foreign_key: "hidden_by"
  belongs_to :featurer, class_name: "User", foreign_key: "featured_by"

  PRINT_PRIVACIES = %w(Public Closed Private)
  enum privacy: [ :priv_public, :priv_closed, :priv_private ]
  enum note_type: [ :html_content, :url_frame ]

  scope :visible, -> { where(hidden: nil) }
  scope :featured, -> { where.not(featured: nil) }
  scope :featured_front, -> { priv_public.html_content.featured.order(created_at: :desc).limit(6) }

  validates :title, :user_id, :privacy, :content, presence: true
  validates :note_type, inclusion: { in: %w(html_content url_frame) }
  validates :privacy, inclusion: { in: %w(priv_public priv_closed priv_private),
    message: "%{value} is not a valid privacy level" }
  validates :title, length: { in: 1..200 }
  validates :content, length: { in: 1..100000,
    too_long: "too large, consider splitting into multiple notes or linking an external document" }
  validates :content, format: { with: URL_REGEXP,
    message: "must be valid web url" }, if: :url_frame?

  validates :hidden_reason, length: { in: 1..200 }, if: :hidden
  validate :fully_hidden

  before_save :set_short_text

  attr_readonly :note_type
  attr_readonly :forked_from

  # Custom validations
  def fully_hidden # All hidden must be set or none
    attrs = [hidden, hidden_by, hidden_reason]
    logger.info attrs
    errors.add(:base, "must have hidden, hidden reason and hider.") unless attrs.all? || attrs.none?
  end

  # Misc methods
  def editable
    created_at > 1.day.ago || priv_private? || hidden?
  end

  def fork_note
    self.class.new({
      note_type: note_type,
      content: content,
      title: "Copy of: " + title,
      privacy: privacy,
      forked_from: id
    })
  end

  # def get_forks_for_api
  #   Note.priv_public.where(forked_from: id).select(:id, :title)
  # end

  def time_for_display
    created_at > 7.days.ago ? time_ago_in_words(created_at) : created_at.strftime("%F")
  end

  def set_short_text
    # TODO Fix the... well all of this...
    return unless content_changed?
    if html_content?
      # TODO look actual errors
      begin
        self.short_text = Nokogiri::HTML(content).text[ 0, 600 ].gsub(/\W+/, " ")
      rescue
        self.short_text = self.title
      end
    else
      self.short_text = self.title
    end
  end

  def view_from(user, sess, ip)
    Thread.new do
      ActiveRecord::Base.connection_pool.with_connection do |conn|
        p = page_views.create(
          session_id: sess,
          ip_address: ip,
          user: user
        )
      end
    end
  end

  def privacy_string
    PRINT_PRIVACIES[self['privacy']]
  end

  def feature!(u)
    self.featured = Time.now
    self.featurer = u
  end

  def unfeature!
    self.featured = nil
    self.featurer = nil
  end

  def hide!(u, reason)
    self.hidden = Time.now
    self.hider = u
    self.hidden_reason = reason
  end

  def unhide!
    self.hidden_reason = nil
    self.hider = nil
    self.hidden = nil
  end

  def viewable_by?(viewer)
    return true if viewer && viewer.id == user_id # Always if creator
    # Must NOT be private and (NOT be hidden Or otherwise viewer must be an admin)
    !priv_private? && (!hidden? || (viewer && viewer.admin?))
  end

  # Class methods

  def self.viewable_publicly(viewer)
    q = priv_public
    viewer.admin? ? q : q.visible
  end

  ###########
  # Workers #
  ###########
  def self.count_page_views
    # Get the note ids of page_views which aren't cached already,
    pv_note_ids = PageView.for_notes
      .not_note_cached
      .pluck(:viewable_id)

    return job_msg("0") unless pv_note_ids.size > 0

    # Update the view_count of each note in the list to the
    # total length of its views.
    note_count = Note.where(id: pv_note_ids.uniq)
      .includes(:page_views)
      .each { |note| note.update(view_count: note.page_views.size) }.size

    # Mark page_views as cached
    PageView.not_note_cached.update_all(count_cached: true)

    job_msg("#{pv_note_ids.size} new views on #{note_count} unique notes")
  end

  def self.cache_votes
    # Get non-cached vote ids
    vote_note_ids = Vote.for_notes
      .not_note_cached
      .pluck(:votable_id)

    return job_msg("0") unless vote_note_ids.size > 0

    note_count = Note.where(id: vote_note_ids.uniq)
      .includes(:votes)
      .each { |note| note.update(vote_cache: note.votes.size) }.size

    Vote.not_note_cached.update_all(cached: true)

    job_msg("#{vote_note_ids.size} new votes on #{note_count} unique notes")
  end
end

app/controllers/admin/notes_controller.rb
class Admin::NotesController < AdminController
  before_filter :find_model

  def show
    if @note.hidden?
      @hider = current_user if current_user.id == @note.hidden_by
      @hider ||= @note.hider
    end
    if @note.featured?
      @featurer = current_user if current_user.id == @note.featured_by
      @featurer ||= @note.featurer
    end
    render 'show', layout: @layout
  end

  def hide # Not the opposite of show :)
    @note.hide!(current_user, note_params[:hidden_reason])
    @note.unfeature! # Hiding a note unfeatures it
    if try_save('Note hidden.')
      @note.user.add_notification(
        @note,
        :note_hidden,
        "Your note: '#{@note.title.truncate(30)}', was hidden by an admin. "\
        "Click here to find out why."
      )
    end
  end

  def unhide
    @note.unhide!
    if try_save('Note unhidden.')
      @note.user.add_notification(
        @note,
        :note_hidden,
        "Your note: '#{@note.title.truncate(30)}', was unhidden."
      )
    end
  end

  def feature
    return redirect_to @note, notice: "Can't feature hidden note" if @note.hidden?
    @note.feature!(current_user)
    if try_save('Note now featured.')
      @note.user.add_notification(
        @note,
        :note_featured,
        "Well done! Your note '#{@note.title.truncate(30)}' was featured by "\
        "an admin. It will now appear on the front page of the site!"
      )
    end
  end

  def unfeature
    @note.unfeature!
    try_save('Note unfeatured.')
  end

private
  def find_model
    @note = Note.find_by_id(params[:id]) if params[:id]
  end

  def note_params
    params.require(:note).permit(:hidden_reason)
  end

  def try_save(msg)
    if @note.save
      redirect_to @note, notice: msg
    else
      render action: 'show'
      false
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :set_note,                only: [:show, :edit, :update, :destroy, :forks]
  before_action :must_be_creator,         only: [:edit, :update, :destroy]
  before_action :must_be_editable,        only: [:edit, :update]
  before_action :must_be_viewable,        only: [:show, :forks]

  def index
    @title = "Explore Notes"

    @sort_types = ["popular", "views", "latest", "oldest", "title"]
    if params[:sort]
      if (@sort_types.include? params[:sort])
        @sort = params[:sort]
      else
        flash[:alert] = "Invalid sort type."
      end
    end
    @sort ||= "popular"

    q = Note.viewable_publicly(current_user) # <= very important

    @search_q = params[:q]
    if @search_q && @search_q.length > 0
      if @search_q.length < 100
        q = q.search_by_title_short_text(@search_q)
      else
        flash[:alert] = "Search query must be less than 100 characters"
      end
    end

    case @sort
    when "views"
      q = q.order(view_count: :desc)
    when "latest"
      q = q.order(created_at: :desc)
    when "oldest"
      q = q.order(created_at: :asc)
    when "title"
      q = q.order(:title)
    else
      # popular
      q = q.order(vote_cache: :desc, created_at: :desc)
    end

    @notes = q.sexcept(:content).page(params[:page]).per(10).includes(:user)
  end

  def new
    @title = "Create note"

    forking_id = params[:forking].to_i
    if forking_id > 0 && (forking = Note.find_by_id(params[:forking]))
      @note = forking.fork_note
      return render 'new'
    end
    # If it reaches this point with an attemted fork:
    flash[:notice] = "Could not fork note with id \'#{params[:forking]}\'" if params[:forking]
    type = params[:type]
    if type && Note.note_types.include?(type)
      @note = Note.new(note_type: type)
      render 'new'
    else
      flash[:alert] = "Invalid note type" if type
      render 'choose_type'
    end
  end

  def create
    @note = current_user.notes.new(note_params)

    @note.valid? # Putting this in the else section gets captcha error overwritten :(
    if verify_recaptcha(model: @note, message: "Incorrect Captcha.") && @note.save
      redirect_to @note, notice: 'Note saved'
      if @note.original_fork && (current_user.id != @note.original_fork.user_id)
        @note.original_fork.user.add_notification(
          @note,
          :fork_note,
          "#{current_user.name} forked your note: '#{@note.original_fork.title.truncate(30)}'"
        )
      end
    else
      render action: 'new'
    end
  end

  # For one particular note
  def show
    @title = view_context.truncate(@note.title, length: 20)

    @is_creator = is_creator?
    unless @is_creator
      @note.view_from(current_user, session[:session_id], request.remote_ip)
    end
    @disqus_id = "note-#{@note.id}"
    @disqus_title = view_context.truncate(@note.title, length: 60)
    if @note.forked_from
      @original_fork = @note.original_fork
    end
    @user_has_voted = current_user && @note.votes.where(user_id: current_user.id).first
  end

  def edit
    @title = "Edit #{view_context.truncate(@note.title, length: 20)}"
  end

  def update
    if @note.update(note_params)
      redirect_to @note, notice: 'Note updated'
    else
      render action: 'edit'
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_url, notice: "Note deleted"
  end

  def forks
    @notes = @note.forks.viewable_publicly(current_user)
                  .order(created_at: :desc).page(params[:page]).per(10).load
    respond_to do |f|
      f.html do    
        render 'forks', layout: @layout
      end
      # f.json do
      #   render json: @notes
      # end
    end
  end

  NOTE_ERROR = "Error accessing note."

  private
    def set_note
      @note = Note.find_by_id(params[:id])
      return redirect_to notes_path, alert: NOTE_ERROR unless @note
    end

    def note_params
      params.require(:note).permit(:title, :content, :privacy, :note_type, :forked_from)
    end

    # Permissions
    def is_creator?
      current_user && @note.user_id == current_user.id
    end

    def must_be_creator
      return redirect_to @note, alert: NOTE_ERROR unless is_creator?
    end

    def must_be_editable
      redirect_to @note, alert: "You may not edit a public note more than 24 hours after creation." unless @note.editable
    end

    def must_be_viewable
      return redirect_to notes_path, alert: NOTE_ERROR unless @note.viewable_by?(current_user)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_editor_instructions.html.erb
<div class="well well-sm note-instructions">
  If you want to insert an image of your notes, a photo to go with them:
  Click the picture button (<i class="fa fa-picture-o"></i>) to upload an image or give the URL to one.
</div>

app/views/notes/_form.html.erb
<% if @note.html_content? %>
  <script type="text/javascript">
    if (sn.summerNote.loaded) {
      sn.loadSummerNoteEditor();
    } else {
      //Style
      $('head').append( $('<link rel="stylesheet" type="text/css" />').attr('href', sn.summerNote.css) );
      sn.summerNote.loaded = true;
      //JS
      $.getScript(sn.summerNote.js, function() {
        sn.loadSummerNoteEditor();
      });
    }
  </script>
<% end %>

<%= form_for(@note) do |f| %>
  <%= f.hidden_field :note_type %>
  <%= f.hidden_field :forked_from %>
  <div class="row">
    <div class="col-md-3">
      <% if @note.errors.any? %>
        <div class="saving-errors panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@note.errors.count, "error") %>:</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @note.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control", placeholder: "How the universe came about" %>
      </div>
      <div class="form-group">
        <%= f.label :privacy %>
        <%= f.select :privacy, [
          ['Public', 'priv_public'],
          ['Closed', 'priv_closed'],
          ['Private', 'priv_private']], {},
          {class: "form-control"}
        %>
      </div>
      <div class="well well-sm note-tips">
        <strong>Remember:</strong>
        Be descriptive when choosing a note title. People need to be able to find it.
        <dl>
          <dt>Public</dt>
          <dd>Anyone can find and view</dd>
          <dt>Closed</dt>
          <dd>Anyone with a link can view</dd>
          <dt>Private</dt>
          <dd>Only you have access</dd>
        </dl>
      </div>
      <%= render 'captcha' if @note.new_record? %>
      <%= f.submit class: "btn btn-success btn-block" %>
    </div>
    <div class="col-md-9">
      <%# f.label :content %>
      <% if @note.html_content? %>
        <%= f.text_area :content, id: "note-content", class: "summernote-main" %>
        <%= render 'editor_instructions' %>
      <% else %>
        <div class="form-group">
          <%= f.label :content, "Url to notes", placeholder: "http://example.com/notes.pdf" %>
          <%= f.text_area :content, class: "form-control" %>
        </div>
        <%= render 'link_instructions' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/notes/_link_instructions.html.erb
<div class="well well-sm note-instructions">
  <h4>Only links to pages using https are accepted.</h4>
  <p>Also make sure the link you are supplying is <strong>accessible to anyone</strong> (e.g. you don't have to be signed in) and that it is the most <strong>direct link</strong> possible to the content.</p>
  <p>We reccomend you verify this by loading the url in private browsing to check that there is no access condition on it.</p>
</div>

<div class="well well-sm">
  <h3>Instructions for some sites:</h3>
  <p>
    <h4>OneDrive/SkyDrive:</h4>
    <ol>
      <li>Open your document in the online editor (Word Online, PowerPoint Online etc.).</li>  
      <li>Click 'File' <i class="fa fa-arrow-right"></i> 'Share' <i class="fa fa-arrow-right"></i> 'Embed'.</li>
      <li>
        Once you press 'Generate', you will be given an Embed Code that looks like:
        <pre>&lt;iframe src='<strong><u>https://onedrive.live.com/embed?cid=7A2FE2A742659A87&amp;resid=7A2FE2A742659A87%21232&amp;authkey=AFvEMqPZbq7DE2g&amp;em=2&amp;wdStartOn=1</u></strong>' width='476px' height='288px' frameborder='0'&gt;This is an embedded &lt;a target='_blank' href='http://office.com'&gt;Microsoft Office&lt;/a&gt; document, powered by &lt;a target='_blank' href='http://office.com/webapps'&gt;Office Online&lt;/a&gt;.&lt;/iframe&gt;</pre>
      </li>
      <li>Copy out the part of <strong>your code</strong> that is in the same place as the part underlined above.</li>
      <li>Paste it into the Url box above.</li>
    </ol>
  </p>

  <p>
    <h4>Google Drive/Docs:</h4>
    <ol>
      <li>Open your document in the online editor:</li>  
      <li>Click 'File' <i class="fa fa-arrow-right"></i> 'Publish to the web'.</li>
      <li>Make sure 'Require viewers to sign in' is not ticked.</li>
      <li>Copy the link given.</li>
      <li>Paste it into the Url box above.</li>      
    </ol>
  </p>
</div>

app/views/notes/_small_list.html.erb
<ul class="list-group small-notes-list">
  <% if @notes.any? %>
    <% @notes.each do |n| %>
      <%= link_to n, class: "list-group-item" do %>
        <div class="note-title">
          <div class="note-list-info pull-right text-right">
            <span class="text-muted created-at"><%= n.time_for_display %></span>
            <%= noteworthies(n.vote_cache) %>
          </div>
          <%= n.title %>
          <%= content_tag(:span, n.privacy_string, class: "label label-default") unless n.priv_public? %>
          <%= note_hidden if n.hidden? %>
          <%= note_featured if n.featured? %>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <% if block_given? %>
      <%= yield %>
    <% else %>
      <li class="list-group-item">No Notes</li>
    <% end %>
  <% end %>
</ul>
<div class="text-center"><%= paginate @notes %></div>

app/views/notes/choose_type.html.erb
<h2 class="text-center">Choose a note type:</h2>

<div class="row choose-note-type">
  <div class="col-md-2"></div>
  <div class="col-md-4">
    <%= link_to new_note_path(type: "html_content"), class: "well well-sm" do %>
      <h3>Edit on StudyNet</h3>
      You can create and edit the content of the note right on this site with a built in word processor.
      If want to upload a photo of the notes, you may do so here.
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to new_note_path(type: "url_frame"), class: "well well-sm" do %>
      <h3>External Link</h3>
      Have your note as a reference to another document or page on the web by supplying a link to it.
      This could be a pdf, OneDrive document, etc.
    <% end %>
  </div>
  <div class="col-md-2"></div>
</div>

app/views/notes/edit.html.erb
<h3>Edit note</h3>

<%= render 'form' %>

app/views/notes/forks.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <%= close_modal %>
      <h4 class="modal-title text-center">
        <i class="fa fa-code-fork"></i> Forks of '<%= link_to @note.title, @note %>'
      </h4>
    </div>
    <div class="modal-body">
      <%= render layout: 'notes/small_list' do %>
        <li class="list-group-item">
          <h4 class="text-center">
            This note hasn't been forked yet!
          </h4>
          <p>
            Forking a note creates an identical copy of the note on your profile for you to edit.
            This is useful if for example you wanted to make an alternate version of a note
            or fix errors you believe to be in original.
            <br>
            Click the 
            <a class="btn btn-default ttp btn-sm pointer" title="Creates an identical copy which you can edit.">
              <i class="fa fa-code-fork"></i> Fork
            </a>
            button at the top left of a note to create a fork of the one you are viewing.
          </p>
        </li>
      <% end %>
    </div>
  </div>
</div>

app/views/notes/index.html.erb
<h2>Explore Notes</h2>
<div class="panel panel-default filter-notes">
  <div class="panel-body">
    <div class="row">
      <div class="col-sm-8 sort-options">
        <strong>Sort:</strong>
        <% @sort_types.each do |st| %>
          <%= current_filter st, params.merge(:sort => st), class: "filter-option" %>
        <% end %>
      </div>
      <div class="col-sm-4">
        <form class="form-inline pull-right" role="form">
          <div class="input-group">
            <%= text_field_tag 'q', @search_q, class: "form-control", placeholder: "Search..." %>
            <span class="input-group-btn">
              <button type="submit" class="btn btn-default"><%= i "search" %></button>
            </span>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<ul class="list-unstyled">
  <% @notes.each do |n| %>
    <li class="listed-note">
      <div class="row">
        <%= link_to n do %>
          <p class="lead col-sm-7"><%= truncate(n.title, length: 60) %></p>
        <% end %>
        <div class="col-sm-5 text-right">
          <%# content_tag :div, nil, class: "vote note-vote pull-right", data: { avg: n.total_score } LOL, star ratings %>
          <%# note_featured if n.featured? Deciding not to here %>
          <%= note_hidden if n.hidden? %>
          <%= noteworthies n.vote_cache %>
          <div><small class="text-muted">
            <% if n.forked_from %>
              <%= i "code-fork", title: "This note was forked from another one." %>
            <% end %>
            <%= n.time_for_display %>
            <b><%= link_to n.user.name, n.user %></b>
          </small></div>
        </div>
      </div>
    </li>
  <% end %>
  <%= content_tag(:h4, "No notes to show") unless @notes.any? %>
</ul>
<%= paginate @notes %>
<br>
<div class="text-center">
  <%= link_to "Post your own notes!", new_note_path, class: "btn btn-success" %>
</div>

app/views/notes/new.html.erb
<h3>Create a note:</h3>

<%= render 'form' %>

app/views/notes/show.html.erb
<h2 class="note-heading-info">
  <%= @note.title %>
  <small>
    <%= content_tag :span, @note.privacy_string, class: "label label-default" unless @note.priv_public? %>
    <%= note_hidden if @note.hidden? %>
    <%= note_featured if @note.featured? %>
    <% if @original_fork %>
      <span class="tpp" title="The note was copyed and likely edited from another one.">
        Forked
      </span>
    <% else %>
      Posted
    <% end %>
    by <%= @is_creator ? "You" : (link_to @note.user.name, @note.user) %>
    <% if @original_fork %>
      from
      <%= link_to truncate(@original_fork.title, length: 15), @original_fork %>
    <% end %>
    <%= @note.time_for_display %>
  </small>
</h2>

<%= content_tag :div, class: "well well-sm" do %>
  <strong>Note was hidden by admin because:</strong>
  "<%= @note.hidden_reason %>"
  <br>
  You may edit a note while it's hidden to fix anything to get it visible again.
<% end if @note.hidden? %>

<div class="panel panel-default note-view">
  <div class="panel-heading note-options">
    <div class="btn-group">
      <%= link_to new_note_path(forking: @note.id), class: "btn btn-default ttp mbs",
            title: "Creates an identical copy which you can edit." do %>
        <%= i "code-fork" %> Fork
      <% end %>

      <% if @note.url_frame? %>
        <%= link_to @note.content, class: "btn btn-default ttp",
              title: "View content on original site (new tab).", target: "_blank" do %>
          <%= i "globe" %> Original
        <% end %>
      <% end %>

      <%= link_to "Admin", admin_note_path(@note), class: "btn btn-warning remote-modal" if current_user.try(:admin?) %>

      <% if @is_creator %>
        <%= link_to 'Delete', note_path(@note), method: :delete, class: "btn btn-danger",
                    data: { confirm: 'Confirm deletion of note?' } %>
        <% if @note.editable %>
          <%= link_to 'Edit', edit_note_path(@note), class: 'btn btn-info' %>
        <% else %>
          <span class="ttp" title="You may only edit public posts within 24 hours of creation." data-toggle="tooltip">
            <%= link_to 'Edit', edit_note_path(@note), class: 'btn btn-info disabled edit-btn' %>
          </span>
        <% end %>
      <% end %>
    </div>

    <% if @is_creator || !current_user %>
      <%= content_tag :button, class: "btn btn-default pull-right creator-noteworthy not-nw disabled ttp mbs",
            title: @is_creator ? "You may not noteworthy your own note." : "You must sign in to noteworthy." do %>
        <%= i "star" %>
        <span class="vote-count"><%= @note.vote_cache %></span>
      <% end %>
    <% else %>
      <%= content_tag :button, data: { note_id: @note.id },
            class: "btn btn-default pull-right noteworthy #{@user_has_voted ? 'is-nw' : 'not-nw'}" do %>
        <%= i "star" %>
        Noteworthy
        <span class="vote-count"><%= @note.vote_cache %></span>
      <% end %>
    <% end %>
    <div class="clearfix"></div>
  </div>
  <% if @note.html_content? %>
    <div class="panel-body note-content html-content">
      <%= @note.content.html_safe %>
    </div>
  <% elsif @note.url_frame? %>
    <div class="panel-body note-content no-padding">
      <%= content_tag(:iframe, "", src: @note.content, class: "note-iframe") %>
    </div>
  <% else %>
    <div class="alert alert-danger">Error displaying note. (no note type)</div>
  <% end %>

  <div class="panel-footer no-padding">
    <span class="view-count">
      <strong>Views:</strong>
      <%= number_with_delimiter @note.view_count %>
    </span>
    |
    <span class="note-link">
      <strong>link:</strong>
      <%= link_to note_url(@note) do %>
        <code><%= note_url(@note) %></code>
      <% end %>
    </span>
    |
    <%= link_to "Forks", forks_note_path(@note), class: "remote-modal" %>
  </div>
</div>

<%= render "disqus" %>