config/routes.rb
StudyNetwork::Application.routes.draw do
  devise_for :users, :skip => [:sessions, :registrations]
  as :user do
    match "login" =>        "sessions#new", as: :new_user_session, via: [:get, :post] # sending to custom sessions for modal option
    post "login_user" =>    "sessions#create", as: :user_session
    delete "logout_user" => "sessions#destroy", as: :destroy_user_session

    get "/register" =>    "registrations#new", as: :new_user_registration
    get "/u/edit" =>      "registrations#edit", as: :edit_user_registration
    post "/register" =>   "registrations#create", as: :user_registration
    patch "/register" =>  "registrations#update"
    put "/register" =>    "registrations#update"
    delete "/register" => "registrations#destroy"

    get "/u/delete_account" => "registrations#delete_account", via: :get

    get "/u/:id" => "registrations#show", as: :user
  end

  resources :n, as: :notes, controller: :notes do
    member do
      get "forks"
    end
  end

  namespace :admin do
    scope "n", as: "note" do
      get ":id" =>             "notes#show"
      patch ":id/hide" =>      "notes#hide", as: :hide
      patch ":id/unhide" =>    "notes#unhide", as: :unhide
      patch ":id/feature" =>   "notes#feature", as: :feature
      patch ":id/unfeature" => "notes#unfeature", as: :unfeature
    end
  end

  match "goals/info" => "goals#info", as: :goals_info, via: [:get, :post]
  resources :goals do
    member do
      post   "t" =>    :create_todo
      put    ":tid" => :update_todo
      delete ":tid" => :destroy_todo
    end
  end

  get "/notifications" =>       "notifications#index", as: :notifications
  get "/notifications/count" => "notifications#count"
  get "/notifications/:id" =>   "notifications#show", as: :notification
  
  post "/v/:model/:id/:value" => "votes#create"

  get "/about" =>     "home#about"
  get "/changelog" => "home#changelog"

  get "/nw" => "home#marked_as_nw", as: :nw

  root "home#index"

  get "bgoals" => "home#beta"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, except: [:marked_as_nw, :show_user]

  def index
    if current_user
      # DASHBOARD
      @user = current_user
      @dash = true
      @notes = @user.notes.order(created_at: :desc).page(params[:page]).per(10).load
      @medals = @user.medals
      render 'dashboard'
    else
      # Landing page
      @no_container = true
      render 'index_no_user'
    end
  end

  def modal
    @is_modal = true
    if ['login', 'register', 'goals_info', 'delete_account'].include? params[:modal_type]
      render 'modal/' + params[:modal_type], layout: false
    else
      render text: '404 modal not found', status: 404
    end
  end

  def about
    @title = "About"
  end

  def changelog
    @title = "Changelog"
    @versions = $version_hsh["versions"]
    @upcoming = $version_hsh["upcoming"]
  end

  def beta
    render 'index'
  end

  def marked_as_nw
    @title = "Noteworthies"
    @notes = current_user.noteworthies.order("votes.created_at DESC").page(params[:page]).per(10).load
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_fb_like.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-like" data-href="https://www.facebook.com/studynet.me" data-layout="standard" data-action="like" data-show-faces="false" data-share="true"></div>

app/views/home/_featured_notes.html.erb
<div class="row featured-notes">
  <h3><%= note_featured %> Featured notes:</h3>
  <% Note.featured_front.each do |n| %>
    <div class="col-lg-2 col-md-3 col-sm-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="note-title">
            <span class="pull-right"><%= noteworthies(n.vote_cache) %></span>
            <%= truncate(n.title, length: 40) %>
          </div>
        </div>
        <div class="panel-body">
          <%= truncate(n.short_text, length: 200) %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/home/about.html.erb
<h1 class="text-danger text-center">Project now inactive :(</h1>

<h1>About</h1>

<p class="lead">StudyNet is a study social network and the first of its kind.</p>

It was created by Conor Bolger, Rory Hughes and Sean Murphy. Conor and Sean are 1st year Trinity College students and Rory is a 5th year Gonzaga College student.

<h2>Founders</h2>
<div class="founders row">
  <div class="col-sm-4" title="Sean">
    <h3>Sean</h3>
    <img src="/sean.jpeg" alt="Sean" class="img-circle">
    <p>
      <strong>sean</strong> at <strong>studynet</strong> dot <strong>me</strong>
    </p>
  </div>
  <div class="col-sm-4" title="Rory">
    <h3>Rory</h3>
    <img src="/rory.jpeg" alt="Rory" class="img-circle">
    <p>
      <strong>rory</strong> at <strong>studynet</strong> dot <strong>me</strong>
    </p>
  </div>
  <div class="col-sm-4" title="Conor">
    <h3>Conor</h3>
    <img src="/conor.jpeg" alt="Conor" class="img-circle">
    <p>
      <strong>conor</strong> at <strong>studynet</strong> dot <strong>me</strong>
    </p>
  </div>
</div>

<br>
The Web App was created to combat the difficulties that 2nd and 3rd level students face when it comes to study. It gives users the ability to access notes, join private groups, create personal timetables, set goals and access past exam papers and solutions. 
StudyNet aims to be the study site that 2nd and 3rd level students worldwide use to achieve their best in exams.

<h2>FAQ:</h2>

<dl>
  <dt>What is 'forking a note'?</dt>
  <dd>
    Forking a note is creating a copy of the note on your profile which you can edit.
    This is useful for example if you want to make edits or improvement of your own.
    Forking a note also references the original one, giving credit to the author.
  </dd>
  <dt>When I mark something as 'noteworthy' and refresh, it doesn't count my vote.</dt>
  <dd>
    The votes placed take a maximum of one minute to process.
    After that, your vote should be added to the total.
    If you are sure that it isn't changing as a consequence of you voting, send an email to Rory (above).
  </dd>
  <dt>Is there a StudyNet smartphone app?</dt>
  <dd>
    At this moment unfortunately not.
    However, we do expect to release one soon.
    We want to get the web app fully functional first before we start building the mobile version.
    If you do need to access StudyNet on the go, the site is optimised for mobile devices and should run well in the web browser on most smartphones.
  </dd>
</dl>

<h3><%= link_to "Change Log/Versions", changelog_path %></h3>

app/views/home/changelog.html.erb
<h3>Changelog</h3>

<% @versions.each do |v| %>
  <h5><%= v["version_str"] %> <small><%= v["date"].strftime("%A, %F at %T") %></small></h5>
  <ul>
    <% v["changes"].each do |c| %>
      <li><%= c %></li>
    <% end %>
  </ul>
<% end %>

<h3>Upcoming features</h3>

<% @upcoming.each do |f| %>
  <h4><%= f["title"] %></h4>
  <p><%= f["desc"] %></p>
<% end %>

app/views/home/dashboard.html.erb
<div class="row dashboard">
  <div class="col-sm-4">
    <%= render 'devise/registrations/user_info' %>
    <div class="places">
      <%= link_to nw_path, class: "btn btn-default", title: "Note you have marked Noteworthy" do %>
        <i class="fa fa-star"></i> Noteworthies
      <% end %>
      <%= link_to new_note_path, class: "btn btn-default" do %>
        <i class="fa fa-file"></i> Create Note
      <% end %>
      <%= link_to goals_path, class: "btn btn-default" do %>
        <i class="fa fa-list"></i> Goals
      <% end %>
      <%= link_to notifications_path, class: "btn btn-default" do %>
        <i class="fa fa-bell-o"></i> Notifications
        <span class="label label-danger">New</span>
      <% end %>
      <%= link_to edit_user_registration_path, class: "btn btn-default" do %>
        <i class="fa fa-cogs"></i> Account Settings
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete, class: "btn btn-default" do %>
        <i class="fa fa-sign-out"></i> Logout
      <% end %>
    </div>
  </div>
  <div class="col-sm-8">
    <h3>Notes created by you:</h3>
    <%= render layout: 'notes/small_list' do %>
      <%= link_to "You haven't created any notes! Click here to do so now.", new_note_path, class: "list-group-item" %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<h2>Goals and timetables coming soon</h2>

<div class="row">
  <div class="col-md-8">
    <h3>My study timetable</h3>
    <table class="table">
      <tr><td>#</td><td>Sunday</td><td>Monday</td><td>Tuesday</td><td>Wednesday</td><td>Thursday</td><td>Fridays</td><td>Saturday</td></tr>
      <tr><td>8</td><td></td><td>School</td><td>School</td><td>School</td><td>School</td><td>School</td><td></td></tr>
      <tr><td>9</td><td></td><td>School</td><td>School</td><td>School</td><td>School</td><td>School</td><td></td></tr>
      <tr><td>10</td><td>Football Match</td><td>School</td><td>School</td><td>School</td><td>School</td><td>School</td><td></td></tr>
      <tr><td>11</td><td>Football Match</td><td>School</td><td>School</td><td>School</td><td>School</td><td>School</td><td>History </td></tr>
      <tr><td>12</td><td>Football Match</td><td>School</td><td>School</td><td>School</td><td>School</td><td>School</td><td>French</td></tr>
      <tr><td>13</td><td></td><td>School</td><td>School</td><td>School</td><td>School</td><td>School</td><td></td></tr>
      <tr><td>14</td><td>Maths</td><td>School</td><td>School</td><td></td><td>School</td><td>School</td><td>Geography</td></tr>
      <tr><td>15</td><td>Geography</td><td>School</td><td>School</td><td>Ultimate Frisbee</td><td>School</td><td>School</td><td>Maths</td></tr>
      <tr><td>16</td><td>Chemistry</td><td></td><td></td><td>Ultimate Frisbee</td><td></td><td></td><td></td></tr>
      <tr><td>17</td><td></td><td>Irish</td><td>History</td><td></td><td>Business</td><td>Geography</td><td>Physics</td></tr>
      <tr><td>18</td><td>French Vocab</td><td>Maths</td><td>Maths</td><td>Irish</td><td>Business</td><td>Maths</td><td></td></tr>
      <tr><td>19</td><td></td><td>Physics</td><td>Football Training</td><td>Latin</td><td>Physics</td><td></td><td>Relax :)</td></tr>
      <tr><td>20</td><td></td><td></td><td>Football Training</td><td></td><td></td><td>Latin</td><td></td></tr>
      <tr><td>21</td><td></td><td>Latin</td><td></td><td></td><td>Physics</td><td></td><td></td></tr>
      <tr><td></td></tr>
    </table>

  </div>
  <div class="col-md-4">
    <h3>Goal progress</h3>
    <div class="panel-group">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent=".panel-group" href="#collapseOne">
              French Exam
              <span class="pull-right text-info">50%</span>
            </a>
          </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse">
          <div class="panel-body">
            <div class="progress progress-striped">
              <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%">
                <span class="sr-only">50% Complete (success)</span>
              </div>
            </div>
            <div class="checkbox">
              <label>
                <input type="checkbox" checked>
                Perfect Tense
              </label>
            </div>
            <div class="checkbox">
              <label>
                <input type="checkbox" value="">
                Vocabulary
              </label>
            </div>
            <input placeholder="Add a task..." class="form-control">
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent=".panel-group" href="#collapseTwo">
              Triginometry Study
              <span class="pull-right text-info">75%</span>
            </a>
          </h4>
        </div>
        <div id="collapseTwo" class="panel-collapse collapse">
          <div class="panel-body">
            <div class="progress progress-striped">
              <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%">
                <span class="sr-only">75% Complete (success)</span>
              </div>
            </div>
            <div class="checkbox">
              <label>
                <input type="checkbox" checked>
                Half angle formula
              </label>
            </div>
            <div class="checkbox">
              <label>
                <input type="checkbox" value="">
                Practise Graph drawing
              </label>
            </div>
            <div class="checkbox">
              <label>
                <input type="checkbox" checked>
                Try past paper questions
              </label>
            </div>
            <div class="checkbox">
              <label>
                <input type="checkbox" checked>
                Chapter summary questions
              </label>
            </div>
            <input placeholder="Add a task..." class="form-control">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index_no_user.html.erb
<div class="jumbotron marketing">
  <div class="container">
    <div class="row">
      <div class="col-md-6 basic-info">
        <h2 class="text-center">Finding school stressful?</h2>
        <p class="lead text-center">Use StudyNet to:</p>

        <table class="feature-list list-unstyled lead">
          <tr>
            <td><i class="fa fa-copy"></i></td>
            <td>View and share <strong>notes</strong> with students studying the same subjects.</td>
          </tr>
          <tr>
            <td><i class="fa fa-check-square-o"></i></td>
            <td>Set <strong>goals</strong> and reach your targets.</td>
          </tr>
          <tr>
            <td><i class="fa fa-group"></i></td>
            <td>
              Coming soon: <strong>groups</strong>
              for you and your class to collaborate.
            </td>
          </tr>
          <tr>
            <td><i class="fa fa-calendar"></i></td>
            <td>
              More features upcoming include <strong>study timetables</strong> and
              past <strong>exam paper</strong> integration.
            </td>
          </tr>
        </table>
        <%= link_to "Join StudyNet now!", new_user_registration_path,
            class: "remote-modal btn btn-success btn-lg btn-block join-us" %>
        <%= render "fb_like" %>
      </div>
      <div class="col-md-6">
        <div class="text-center text-muted video-lead">Watch video to learn more...</div>
        <iframe width="100%" class="video" src="//www.youtube.com/embed/yDl30isPpkg?modestbranding=1&showinfo=0&controls=0" frameborder="0" allowfullscreen></iframe>
      </div>
    </div>
  </div>
</div>

<%= render 'featured_notes' %>

app/views/home/marked_as_nw.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6 marked-as-nw">
    <%= link_to root_path, class: "back-to-profile" do %>
      <i class="fa fa-arrow-circle-left"></i> Back to my profile
    <% end %>
    <h2 class="text-center text-success">
      <i class="fa fa-star"></i> Noteworthies
    </h2>
    <p class="text-center"><small>(Notes you have marked as noteworthy)</small></p>

    <%= render layout: 'notes/small_list', link_to_assoc: :votable do %>
      <li class="list-group-item">
      <h4 class="text-center">
        You haven't marked any notes as noteworthy!
      </h4>
      <p>
        <br>
        Click the 
        <button class="btn btn-default btn-sm noteworthy not-nw nw-example">
          <i class="fa fa-star"></i>
          Noteworthy
          <span class="vote-count">5</span>
        </button>
        button at the top right of a note to both <strong>give the creator credit</strong>
        and <strong>bookmark it</strong> to this page for later viewing.
      </p>
      </li>
    <% end %>
  </div>
  <div class="col-md-3"></div>
</div>