config/routes.rb
StudyNetwork::Application.routes.draw do
  devise_for :users, :skip => [:sessions, :registrations]
  as :user do
    match "login" =>        "sessions#new", as: :new_user_session, via: [:get, :post] # sending to custom sessions for modal option
    post "login_user" =>    "sessions#create", as: :user_session
    delete "logout_user" => "sessions#destroy", as: :destroy_user_session

    get "/register" =>    "registrations#new", as: :new_user_registration
    get "/u/edit" =>      "registrations#edit", as: :edit_user_registration
    post "/register" =>   "registrations#create", as: :user_registration
    patch "/register" =>  "registrations#update"
    put "/register" =>    "registrations#update"
    delete "/register" => "registrations#destroy"

    get "/u/delete_account" => "registrations#delete_account", via: :get

    get "/u/:id" => "registrations#show", as: :user
  end

  resources :n, as: :notes, controller: :notes do
    member do
      get "forks"
    end
  end

  namespace :admin do
    scope "n", as: "note" do
      get ":id" =>             "notes#show"
      patch ":id/hide" =>      "notes#hide", as: :hide
      patch ":id/unhide" =>    "notes#unhide", as: :unhide
      patch ":id/feature" =>   "notes#feature", as: :feature
      patch ":id/unfeature" => "notes#unfeature", as: :unfeature
    end
  end

  match "goals/info" => "goals#info", as: :goals_info, via: [:get, :post]
  resources :goals do
    member do
      post   "t" =>    :create_todo
      put    ":tid" => :update_todo
      delete ":tid" => :destroy_todo
    end
  end

  get "/notifications" =>       "notifications#index", as: :notifications
  get "/notifications/count" => "notifications#count"
  get "/notifications/:id" =>   "notifications#show", as: :notification
  
  post "/v/:model/:id/:value" => "votes#create"

  get "/about" =>     "home#about"
  get "/changelog" => "home#changelog"

  get "/nw" => "home#marked_as_nw", as: :nw

  root "home#index"

  get "bgoals" => "home#beta"

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  acts_as_paranoid

  has_many :todos, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :title, length: { in: 1..200 }

  def todos_done
    todos.map(&:done).count(true)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :find_goal, except: [:index, :info, :create]
  before_action :must_be_creator, except: [:index, :info, :create]
  before_action :find_todo, only: [:update_todo, :destroy_todo]

  def index
    @title = "Goals"
    respond_to do |f|
      f.html
      f.json do
        @goals = current_user.goals.order(id: :desc).includes(:todos).order('todos.id DESC')
      end
    end
  end

  def info
    render 'info', layout: @layout
  end

  def show
  end

  def create
    @goal = current_user.goals.new(goal_params)
    if @goal.save
      render json: @goal
    else
      render json: errors(@goal.errors.full_messages), status: 400
    end
  end

  def update
    if @goal.update_attributes(goal_params)
      render json: @goal
    else
      render json: errors(@goal.errors.full_messages), status: 400
    end
  end

  def destroy
    @goal.destroy
    render json: { action: "deleted" }
  end

  def create_todo
    todo = @goal.todos.new(todo_params)
    if todo.save
      render json: todo
    else
      render json: errors(todo.errors.full_messages), status: 400
    end
  end

  def update_todo
    if @todo.update_attributes(todo_params)
      render json: @todo
    else
      render json: errors(@todo.errors.full_messages), status: 400
    end
  end

  def destroy_todo
    @todo.destroy
    render json: { action: "deleted" }
  end

private
  def find_goal
    @goal = Goal.find_by_id(params[:id])
    render json: errors("Cannot find goal.") unless @goal
  end

  def find_todo
    @todo = @goal.todos.find_by_id(params[:tid])
  end

  def must_be_creator
    render json: errors("Cannot find goal."), status: 400 unless current_user.id == @goal.user_id
  end

  def todo_params
    params.require(:todo).permit(:content, :done)
  end

  def goal_params
    puts params
    params.require(:goal).permit(:title, :due_at)
  end

  def errors(e)
    { errors: (e.is_a? Array) ? e : [e] }
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/index.html.erb
<div class="row">
<div class="col-md-2"></div>
<div class="col-md-8" id="goals-app">
  <h1 class="text-center">Goals</h1>
  <div class="well well-sm">
    <form id="add-goal" class="btn-group">
      <div class="btn-toolbar" role="toolbar">
        <div class="input-group add-goal-controls">
          <input class="form-control" type="text"
                  placeholder="What you're working towards...">
          <span class="input-group-btn">
            <button type="submit" class="btn btn-info">
              <i class="fa fa-plus"></i>
            </button>
          </span>
        </div>
        <div class="btn-group misc-options">
          <button type="button" class="btn btn-default reload-goals" title="Reload goals">
            <i class="fa fa-refresh"></i>
          </button>
          <%= link_to goals_info_path, class: "btn btn-default goals-help remote-modal", title: "What's this?" do %>
            <i class="fa fa-question"></i>
          <% end %>
        </div>
      </div>
    </form>
  </div>
  <div class="panel-group goals-list">
  </div>
  <div class="no-goals hidden text-center">
    <h3><i class="fa fa-hand-o-up"></i></h3>
    <h3>You haven't created any Goals yet! Add one above.</h3>
    <h4>Learn more by pressing the <i class="fa fa-question"></i> button.</h4>
  </div>
</div>
<div class="col-md-2"></div>
</div>

<script type="text/javascript">
  sn.l(true);
  sn.loadGoals();
</script>

app/views/goals/info.html.erb
<div class="modal-dialog">
  <%= link_to goals_path, class: "back-to-profile" do %>
    <i class="fa fa-arrow-circle-left"></i> Back to my goals
  <% end unless @is_modal %>
  <div class="modal-content">
    <div class="modal-header">
      <%= close_modal %>
      <h3 class="modal-title text-center">What are Goals?</h3>
    </div>
    <div class="modal-body">
      <h4>StudyNet Goals are designed to help you organise your work.</h4>
      <p>
        Whether it's starting off, staying focused, keeping track of what you've done, need to do or just about anything else, goals are here for you!<br><br>
        You can start off each study period, be it a week or a month, by creating goals.
        Challenging yet optimistic goals will drive you on in your study and help you achieve better results.
      </p>
      <br>
      <strong>How to use it:</strong>
      <br>
      <ul>
        <li>To create a new goal, type a title into the box at the top and press enter.</li>
        <li>The goal will then appear below. You can add tasks by entering a description of what's required in the box at the bottom of the goal.</li>
        <li>Once you complete each task, you can tick it off your list by clicking the <i class="fa fa-square-o"></i> on the left.</li>
        <li>To remove a task from the list, hover over it and click the <i class="fa fa-times-circle g-t-destroy" style="color: #FC3939"></i>.</li>
        <li>To change a goal's title, press the <i class="fa fa-pencil-square-o"></i> button and enter a new one at the top. Hit enter to save.</li>
        <li>If you want to delete a goal (including all of its tasks), press the <i class="fa fa-trash-o"></i>.</li>
        <li>The <i class="fa fa-refresh"></i> button reloads the goal list.</li>
      </ul>

      <small>Your goals are not shared and cannot be accessed by any other users.</small>
    </div>
  </div>
</div>