config/routes.rb
StudyNetwork::Application.routes.draw do
  devise_for :users, :skip => [:sessions, :registrations]
  as :user do
    match "login" =>        "sessions#new", as: :new_user_session, via: [:get, :post] # sending to custom sessions for modal option
    post "login_user" =>    "sessions#create", as: :user_session
    delete "logout_user" => "sessions#destroy", as: :destroy_user_session

    get "/register" =>    "registrations#new", as: :new_user_registration
    get "/u/edit" =>      "registrations#edit", as: :edit_user_registration
    post "/register" =>   "registrations#create", as: :user_registration
    patch "/register" =>  "registrations#update"
    put "/register" =>    "registrations#update"
    delete "/register" => "registrations#destroy"

    get "/u/delete_account" => "registrations#delete_account", via: :get

    get "/u/:id" => "registrations#show", as: :user
  end

  resources :n, as: :notes, controller: :notes do
    member do
      get "forks"
    end
  end

  namespace :admin do
    scope "n", as: "note" do
      get ":id" =>             "notes#show"
      patch ":id/hide" =>      "notes#hide", as: :hide
      patch ":id/unhide" =>    "notes#unhide", as: :unhide
      patch ":id/feature" =>   "notes#feature", as: :feature
      patch ":id/unfeature" => "notes#unfeature", as: :unfeature
    end
  end

  match "goals/info" => "goals#info", as: :goals_info, via: [:get, :post]
  resources :goals do
    member do
      post   "t" =>    :create_todo
      put    ":tid" => :update_todo
      delete ":tid" => :destroy_todo
    end
  end

  get "/notifications" =>       "notifications#index", as: :notifications
  get "/notifications/count" => "notifications#count"
  get "/notifications/:id" =>   "notifications#show", as: :notification
  
  post "/v/:model/:id/:value" => "votes#create"

  get "/about" =>     "home#about"
  get "/changelog" => "home#changelog"

  get "/nw" => "home#marked_as_nw", as: :nw

  root "home#index"

  get "bgoals" => "home#beta"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception if Rails.env.production?

  before_action :authenticate_user!
  before_action :check_if_modal
  before_action :turbolinks?

  MODALS = {
    'sessions' =>      ['new'],
    'registrations' => ['new', 'delete_account', 'notifications'],
    'goals' =>         ['info'],
    "notes" =>         ['forks'],

    # Admin
    'admin/notes' =>   ['show']
  }

  helper_method :n_count, :turbolinks?, :show_n?

  def turbolinks?
    @turbolinks ||= request.headers["X-XHR-Referer"]
  end

  def n_count
    @n_count ||= current_user.n_count
  end

  def show_n?
    !@turbolinks && n_count > 0
  end

protected

  def devise_parameter_sanitizer
    if resource_class == User
      UserParameterSanitizer.new(User, :user, params)
    else
      super
    end
  end

  # Modals
  def in_modal_list?(c, a)
    MODALS[params[:controller]].include? params[:action]
  end

  def check_if_modal
    # if params[:m] == '1' && request.post? && in_modal_list?(params[:controller], params[:action])
    if params[:m] == '1' && in_modal_list?(params[:controller], params[:action])
      @is_modal = true
    else
      @layout = 'application'
    end
  end

  def modal_only
    return raise ActionController::RoutingError.new('Not Found') unless @is_modal
  end

  # def no_layout_check
  #   !(params[:no_layout] || request.headers["X-Requested-With"] == "XMLHttpRequest") && 'application'
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_if_with_block condition, options, html_options={}, &block
    if condition
      link_to options, html_options, &block
    else
      content_tag :a, html_options, &block
    end
  end

  def i(n, title: nil)
    return "" unless n
    content_tag(:i, nil, class: "fa fa-#{n}", title: title)
  end

  def nav_link(*args, &block)
    if current_page?(args[block_given? ? 0 : 1])
      if args.last.is_a? Hash
        args.last[:class] ||= ''
        args.last[:class] += ' current-page'
      else
        args.push({ class: "current-page" })
      end
    end
    link_to *args, &block
  end

  def current_filter(*args)
    if @sort == (args[0])
      if args.last.is_a? Hash
        args.last[:class] ||= ''
        args.last[:class] += ' current-filter'
      else
        args.push({ class: "current-filter" })
      end
    end
    link_to *args
  end

  def medals_content(medals)
    medals.each do |med|
      m = content_tag(:span, class: "fa-stack medal", title: "#{med.capitalize} Medal") do
        i("circle fa-stack-2x #{med}") +
        i("star fa-stack-1x")
      end
      concat m
    end
    return nil
  end

  def close_modal
    button_tag "&times;".html_safe, data: { dismiss: "modal" }, class: "close" if @is_modal
  end

  def note_hidden
    content_tag(:span, class: "label label-warning", title: "Note hidden by admin.") do
      i("exclamation-circle") + " Hidden"
    end
  end

  def note_featured
    content_tag(:span, class: "fa-stack featured-icon", title: "Featured Note") do
      i("certificate fa-stack-2x") +
      content_tag(:span, "S", class: "fa-stack-1x")
    end
  end

  def noteworthies(n)
    content_tag(:span, class: "badge nw") do
      "#{n.to_s} #{i("star")}".html_safe
    end
  end

  # Legacy modal system
  # def smodal(name)
  #   o = render file: "modal/#{name}"
  #   raw(o.sub "&times;", "")
  # end
end

app/views/application/_captcha.html.erb
<div id="dynamic_recaptcha" class="form-group" style="display:none">
  <label>Captcha</label>
  <div id="recaptcha_image"></div>
  <div class="recaptcha_only_if_incorrect_sol" style="color:red">Incorrect please try again</div>

  <span class="recaptcha_only_if_image">Enter the words above:</span>
  <span class="recaptcha_only_if_audio">Enter the numbers you hear:</span>

  <input type="text" id="recaptcha_response_field" name="recaptcha_response_field" class="form-control input-sm" />

  <div class="captcha-options">
    <div title="Get another CAPTCHA">
      <a href="javascript:Recaptcha.reload()"><i class="fa fa-refresh"></i></a>
    </div>
    <div title="Get an audio CAPTCHA" class="recaptcha_only_if_image">
      <a href="javascript:Recaptcha.switch_type('audio')"><i class="fa fa-volume-up"></i></a>
    </div>
    <div title="Get an image CAPTCHA" class="recaptcha_only_if_audio">
      <a href="javascript:Recaptcha.switch_type('image')"><i class="fa fa-picture-o"></i></a>
    </div>
    <div title="Help">
      <a href="javascript:Recaptcha.showhelp()"><i class="fa fa-question-circle"></i></a>
    </div>
    <small>Powered by ReCaptcha</small>
  </div>
</div>
<%= recaptcha_tags ajax: true, display: {theme: 'custom'}, ssl: true %>

app/views/application/_disqus.html.erb
<p class="text-center">
  <%= link_to "Show comments...", request.fullpath, class: "show-disqus" %>
</p>
<div id="disqus_thread"></div>
<script type="text/javascript">
  $(".show-disqus").click(function(e) {
    e.preventDefault();
    $(this).parent().hide();
    if (window.disqus_id) {
      var disqus_shortname = "<%= $keys["disqus"]["shortname"] %>";
      var disqus_identifier = window.disqus_id;
      <% if @disqus_title %>
      var disqus_title = "<%= @disqus_title %>";
      <% end %>

      (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      })();
    }
  });
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "logo-link" do %>
        <img src="/study-net-logo.png" class="site-logo">
      <% end %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= nav_link "Explore Notes", notes_path, class: "mbs" %></li>
        <li><%= nav_link "About", about_path %></li>
      </ul>
      <% if current_user %>
        <ul class="nav navbar-nav navbar-right user-nav">
          <%= render 'notifications' %>
          <li><%= nav_link new_note_path, class: "new-note-nav" do %>
            <i class="fa fa-file-o"></i> New Note
          <% end %></li>
          <li class="dropdown user-dropdown">
            <a class="dropdown-toggle pointer <%= 'current-page' if current_page?(root_path) %>" data-toggle="dropdown">
              <%= current_user.name || "You" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to root_path do %>
                <i class="fa fa-user"></i> My Profile
              <% end %></li>
              <li><%= link_to goals_path do %>
                <i class="fa fa-list"></i> Goals
              <% end %></li>
              <li><%= link_to nw_path do %>
                <i class="fa fa-star"></i> Noteworthies
              <% end %></li>
              <li><%= link_to edit_user_registration_path do %>
                <i class="fa fa-cogs"></i> Account Settings
              <% end %></li>
              <li class="divider"></li>
              <li><%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i> Logout
              <% end %></li>
            </ul>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
        </ul>
        <div class="btn-group navbar-btn pull-right">
          <%= link_to "Create an account", new_user_registration_path, class: "remote-modal btn btn-success" %>
          <%= link_to "Sign in", new_user_session_path, class: "remote-modal btn btn-default" %>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/application/_notifications.html.erb
<li class="dropdown" id="notification-dropdown">
  <a class="dropdown-toggle notification-btn pointer <%= "#{'current-page' if current_page?(notifications_path)} #{show_n? ? 'some' : 'none'}" %>"
    data-toggle="dropdown" title="Notifications">
    <span class="fa-stack">
      <i class="fa fa-stack-1x bell-icon"></i>
      <span class="fa-stack-2x unread"><%= n_count if show_n? %></span>
    </span>
    <span class="notification-label">Notifications</span>
  </a>
  <ul class="dropdown-menu notification-list">
    <li class="text-muted text-center">Loading...</li>
  </ul>
</li>